#ifndef IE_ENUM_H
#define IE_ENUM_H

//___|"ie_enum.h"|______________________________________________________________
//
// Project: Imagine: 3D Environment Engine
// Version: 0.1.0
// Author: David Lipps
// License: MIT License
//
// Copyright (c) 2017 David E Lipps
//______________________________________________________________________________

namespace ie
{
  
  enum IEenum
  {
    //Vertex Attributes
    IE_NULL_ATTRIB, IE_ELEMENT_ATTRIB, IE_POSITION_ATTRIB,
    IE_NORMAL_ATTRIB, IE_MATERIAL_ATTRIB, IE_COLOR_ATTRIB,
    IE_DATA_ATTRIB, IE_DATA1_ATTRIB, IE_DATA2_ATTRIB,
    IE_DATA3_ATTRIB, IE_DATA4_ATTRIB,

    //VBO Formats
    IE_NULL_FORMAT, IE_P_FORMAT, IE_PN_FORMAT,
    IE_PMN_FORMAT, IE_PMNCD_FORMAT, IE_PMNCDD_FORMAT,

    //Obsolete
    IE_NONE_NODE, IE_PLAYER_NODE, IE_CAMERA_NODE, IE_STATIC_NODE,
    IE_TERRAIN_NODE, IE_WATER_NODE,

    //Obsolete
    IE_NONE_RENDER, IE_PLAYER_RENDER, IE_CAMERA_RENDER,
    IE_MATERIAL_RENDER, IE_TEXTURE_RENDER, IE_TERRAIN_RENDER,

    //Obsolete
    IE_NONE_SHADER, IE_STATIC_SHADER, IE_TERRAIN_SHADER,

    //Camera Control Modes
    IE_FIRST_PERSON_MODE, IE_THIRD_PERSON_MODE,
    IE_THIRD_PERSON_RPG_MODE, IE_FLYAROUND_MODE,
    IE_EDITING_MODE,

    //Nexus Messages
    IE_NEXUS_CONNECTION_MSG,
    IE_NEXUS_OUT_CONNECTION_CMD,
    IE_NEXUS_IN_CONNECTION_CMD,
    IE_NEXUS_BI_CONNECTION_CMD,

    //Log Messages
    IE_LOG_MSG,
    IE_LOG_INFO_CMD,
    IE_LOG_WARNING_CMD,
    IE_LOG_DEBUG_CMD,
    IE_LOG_ASSERTION,
    IE_LOG_EXECPTION,

    //System Message
    IE_SYSTEM_MSG,
    IE_SYSTEM_SHUTDOWN_CMD,

    //Subsystem Handles
    IE_ENGINE_ICOM_HANDLE,
    IE_LOG_ICOM_HANDLE,
    IE_CLOCK_ICOM_HANDLE,
    IE_CONTROLLER_ICOM_HANDLE,
    IE_ASSET_MANAGER_ICOM_HANDLE,
    IE_IMPORT_ICOM_HANDLE,
    IE_EDITOR_ICOM_HANDLE,
    IE_TERRAIN_EDITOR_ICOM_HANDLE,
    IE_WAVEFRONT_ICOM_HANDLE,
    IE_GLSL_ICOM_HANDLE,
    IE_VRAM_MANAGER_ICOM_HANDLE,
    IE_RENDER_ENGINE_ICOM_HANDLE,
    IE_PHYSICS_ENGINE_ICOM_HANDLE

  };

}

#endif
